//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guests
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> NumberId { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public Nullable<System.DateTime> DateOfDeparture { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Numbers Numbers { get; set; }
    }
}
